### ISSUE TITLE
Support for more multer config

### ISSUE THREAD

**Issue by larrystone** [IAMOTZ/node-react-cloudinary#2]
I see you are using multer to handle multipart request. Is it possible to provide room for more multer configurations. e.g Image size restrictions, Image type restriction, image storage location and so on?

**Comment by IAMOTZ** [comment]
Hi, @larrystone.
For sure, it is possible to add more Multer configurationS.
Multer is a very useful piece of technology for handling files in the server, it has a set of configuration options that allow you to specify where you want to store files in the server, the number of files to accept, control the type of file that is accepted etc. You can read more about Multer configuration [here](https://github.com/expressjs/multer).

To make things practical, I would be adding the configuration option to enable **image size restriction** to this project. As for image storage location, I won't be doing that since we are storing the image in the cloud.

**TIP**: The best source of knowing all the possible configuration for Multer is its [documentation](https://github.com/expressjs/multer).
